import type { Metadata } from "next";
import "./globals.css";


import {Work_Sans, Quicksand, Karla} from 'next/font/google'

const workSans = Work_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-work-sans',
});

const quicksand = Quicksand({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-quicksand',
});

const karla = Karla({
  subsets: ['latin'],
  weight: ['200', '400', '500', '700'],
  variable: '--font-karla',
});



export const metadata: Metadata = {
  title: "sustainabytes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${workSans.variable} ${karla.variable} ${quicksand.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
